// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://febgiswnbxofljtueqoi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZlYmdpc3duYnhvZmxqdHVlcW9pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4MjE2NDMsImV4cCI6MjA3MDM5NzY0M30.Yn52hXkjnap-5URujmC8Tu0Uns2VN9NCjkNNhsH_1sU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});